DROP TABLE "User";


CREATE TABLE "User"(
	id		VARCHAR(9),
	balance		INTEGER,
	card		INTEGER NOT NULL,
	age		INTEGER NOT NULL CHECK (age > 17),
	email		VARCHAR(50) NOT NULL,
	nombre		VARCHAR(50) NOT NULL,
	password	VARCHAR(50) NOT NULL,
	phone		INTEGER NOT NULL,

CONSTRAINT cp_user PRIMARY KEY(id)
);